countries = ['Afghanistan','America','Albania','Algeria','Argentina','Armenia','Australia','Austria',
        'Azerbaijan','Bahrain','Bangladesh','Belarus','Belgium','Bolivia','Brazil','Bulgaria','Cabo',
        'Cameroon','Canada','Chile','China','Colombia','Costa','Croatia','Cuba','Cyprus','Czechia',
        'Denmark','Dominica','Ecuador','England','Egypt','Estonia','Ethiopia','Finland','France',
        'Germany','Ghana','Greece','Grenada','Honduras','Hungary','Iceland','India','Indonesia',
        'Iran','Iraq','Ireland','Israel','Italy','Jamaica','Japan','Jordan','Kazakhstan','Kenya',
        'Kuwait','Kyrgyzstan','Lebanon','Liberia','Lithuania','Madagascar','Malaysia','Maldives',
        'Mexico','Monaco','Morocco','Mozambique','Myanmar','Nepal','Netherlands','Nigeria','Norway',
        'Oman','Pakistan','Panama','Paraguay','Peru','Philippines','Poland','Portugal','Qatar','Romania',
        'Russian','Saudi','Senegal','Serbia','Singapore','Slovakia','Slovenia','Spain','Sudan','Sweden',
        'Switzerland','Syrian','Tajikistan','Thailand','Tunisia','Turkey','Turkmenistan','Uganda','Ukraine',
        'Uruguay','Uzbekistan','Venezuela','Yemen','Zambia']